### ISSUE TITLE
How can I change initial page from 0 to 1?

### ISSUE THREAD

**Issue by sharad-smi** [uriyyo/fastapi-pagination#53]
I want the initial page number to be 1 instead of 0. In actual use, the first page has page number 1.

How can this be done?

**Comment by uriyyo** [comment]
Hi @sharad-smi,

Could you please try to use this code snippet:
```python
from fastapi_pagination import Page
from fastapi_pagination.bases import AbstractParams, RawParams

class CustomParams(BaseModel, AbstractParams):
    page: int = Query(1, gt=0, description="Page number")
    size: int = Query(50, gt=0, le=100, description="Page size")

    def to_raw_params(self) -> RawParams:
        return RawParams(
            limit=self.size,
            offset=self.size * (self.page - 1),
        )


class CustomPage(Page):
    __params_type__ = CustomParams

```

**Comment by sharad-smi** [comment]
Thank you for the quick response, such an amazing lib, easy to use.

I am new to Python could you please tell me where to add this snippet, I tried adding it before routing but that didn't work.

**Comment by uriyyo** [comment]
Could you provide code which you are using?

This is a fully working example:
```python
from typing import Generic, TypeVar

import uvicorn
from fastapi import Query, FastAPI
from pydantic import BaseModel

from fastapi_pagination import Page, add_pagination, paginate, Params
from fastapi_pagination.bases import RawParams


class CustomParams(Params):
    page: int = Query(1, gt=0, description="Page number")
    size: int = Query(50, gt=0, le=100, description="Page size")

    def to_raw_params(self) -> RawParams:
        return RawParams(
            limit=self.size,
            offset=self.size * (self.page - 1),
        )


T = TypeVar("T")


class CustomPage(Page[T], Generic[T]):
    __params_type__ = CustomParams


app = FastAPI()


class User(BaseModel):
    name: str


users = [User(name=str(i)) for i in range(100)]


@app.get("/", response_model=CustomPage[User])
async def route():
    return paginate(users)


add_pagination(app)

if __name__ == '__main__':
    uvicorn.run("pagination_custom:app")
```

**Comment by sharad-smi** [comment]
Thank you for your kind response. It worked.

My Humble suggestion is to start the page with 1, not from 0. Everywhere the pagination page starts from 1.
Hoe you will keep this suggestion in mind for the future release.

**Comment by uriyyo** [comment]
Thanks, I will take it into account.

**Comment by uselessscat** [comment]
Hi guys,

Im glad I written tests for pagination indexes. This breaks not just our backend tests (7 or 8 tests), also the clients (frontends) that are consuming endpoints using pagination from this library.

So I think this is not a PATCH version update, because is not compatible at all with 0.7.1.

I usually read changelogs when I update major and minor versions, but this was a surprise. Maybe other users will have the same problem. Im just warning. 

Happy coding

**Comment by uriyyo** [comment]
Hi @uselessscat,

I am so sorry to hear that. It was done by mistake (I forget to use `minor` version release scripts instead of `patch` version).

You are totally right, I was planning to release the next `minor` version of `fastapi-pagination` and didn't notice that I have realized `patch` version.

Sorry again, for such troubles. Version `0.7.3.` is released and it has reverted changes for this bug.

Thanks again for pointing on this issue.

**Comment by zdytch** [comment]
So, the feature is reverted now? I still get 0 as the first page. Using 1 over 0 as the first page seems reasonable, since the page index should be synchronized with frontend pagination component.

**Comment by uriyyo** [comment]
Hi @zdytch,

It will be fixed at version `0.8.0` which will be released soon.

**Comment by uriyyo** [comment]
Version `0.8.0` has been realised and it contains fix of this issue.

**Comment by shazz** [comment]
Hi, ah this is what broke my existing code :)
no issue but in this case shouldn't the offset be >=1 (gt=0) and not >=0 (ge=1) ?

```python
offset: conint(ge=0)  # type: ignore
```

**Comment by uriyyo** [comment]
@shazz You are totally right. I will fix it, thanks for pointing this out)
