### ISSUE TITLE
Seek/keyset functionality cancelled?

### ISSUE THREAD

**Issue by chamalis** [uriyyo/fastapi-pagination#843]
Hi,
Is there any reasoning behind removing row-number query type in [#384 ](https://github.com/uriyyo/fastapi-pagination/commit/be1b86d7bf517e3eeb34fecddc0cc117e1035e6a)? 
Theoretically the **seek** pagination is way faster than the **limit/offset**, in Postgresql, due to using the `where` clause instead the `offset` e.g: [[1](https://dba.stackexchange.com/questions/261714/offset-vs-where-performance-for-pagination-with-index)]

Am I missing something?
Thanks!

**Comment by uriyyo** [comment]
Hi @chamalis,
For such cases, I guess `cursor-based` pagination will be a better option.

I ran several different benchmarks and implementation from [#384](https://github.com/uriyyo/fastapi-pagination/commit/be1b86d7bf517e3eeb34fecddc0cc117e1035e6a) was always much slower rather than limit/offset approach.

**Comment by chamalis** [comment]
Hi @uriyyo ,

> I ran several different benchmarks and implementation from [#384](https://github.com/uriyyo/fastapi-pagination/commit/be1b86d7bf517e3eeb34fecddc0cc117e1035e6a) was always much slower rather than limit/offset approach.

Interesting!
Thanks
